### ISSUE TITLE
Activity 5 - TrignometricCalculator

### ISSUE THREAD

**Issue by kiranprabhakar** [MaheshVenom/TestAndroidApp#10]
Create an Calculator with 4 different Trigonometric Functions.

**Comment by kiranprabhakar** [comment]
guys i am implementing sine tangent and cosine functions .. any other means please let me know.. ?

**Comment by pruthvikmutt** [comment]
Kiran,

Its pure Java Coding... I am totally lost with this...

**Comment by kiranprabhakar** [comment]
even same feeling with me.. but we have to go along with it.. it will take us a long way... if not we do nothing at the end! :( ... i am watching coding one by one which ever is required for my app now.. don bother learning java first. it ll be long time.. instead learn on required basis.

**Comment by MaheshVenom** [comment]
Guys please keep emotions out of technical issues.. ;-)

**Comment by kiranprabhakar** [comment]
added cosec, sec, and cot theta functionality

**Comment by kiranprabhakar** [comment]
changed layout from grid to relative so the app looks universal at the end.

**Comment by kiranprabhakar** [comment]
changes pushed to Develop branch in remote : added sec,csec and cot and also changed main activity UI to look little better.

**Comment by kiranprabhakar** [comment]
handled divide by zero exceptions and undefined value exceptions in cse,sec,cot and tan functions.

**Comment by pruthvikmutt** [comment]
Hey,

I just signed the petition "Chief Secretary: Fix to drain water logging on
road - Rachenahalli Lake Road" and wanted to see if you could help by
adding your name.

Our goal is to reach 200 signatures and we need more support. You can read
more and sign the petition here:

http://chng.it/n2QtgqWQMC

Thanks!
Pruthvik
