### ISSUE TITLE
Setup Andriod SDK .

### ISSUE THREAD

**Issue by kiranprabhakar** [MaheshVenom/TestAndroidApp#4]
I have setup the andrioid studio. please setup same and create issue to next member

**Comment by kiranprabhakar** [comment]
@pruthvikmutt and @RajeshChandraShekhar  Please follow same and complete this on priority.

**Comment by kiranprabhakar** [comment]
@NaganandaMeivelan kindly do this soon.

**Comment by NaganandaMeivelan** [comment]
Done

**Comment by pruthvikmutt** [comment]
SDK installed.
