### ISSUE TITLE
Activity 1 - Simple Calculator

### ISSUE THREAD

**Issue by kiranprabhakar** [MaheshVenom/TestAndroidApp#6]
Create an calculator with addition division, multiplication and subtraction.

**Comment by kiranprabhakar** [comment]
@pruthvikmutt @MaheshVenom guys upload your codes to GitHub. so we can start work on merging.

**Comment by MaheshVenom** [comment]
OK I will do it today evening.

**Comment by pruthvikmutt** [comment]
Hi all,

Please find the attached project from my side.

Regards,
Pruthvik.

**Comment by kiranprabhakar** [comment]
@pruthvikmutt where is the attachment?
